version: '3.7'

services:
  app:
    build:
      context: ./docker
      args:
        user: bintzandt
        uid: 1000
    image: test
    container_name: rsc
    working_dir: /var/www/
    volumes:
      - ./:/var/www/

  nginx:
    image: nginx:alpine
    container_name: rsc-nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/

  db:
    image: mysql:8.0
    container_name: rsc-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - db_volume:/var/lib/mysql
    ports:
    - 3306:3306

volumes:
  db_volume:
